/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BranchRouteImport } from './routes/branch'
import { Route as CacheRouteImport } from './routes/cache'
import { Route as FpgaRouteImport } from './routes/fpga'
import { Route as HazardsRouteImport } from './routes/hazards'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as RegistersRouteImport } from './routes/registers'
import { Route as RtlExplorerRouteImport } from './routes/rtl-explorer'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as WaveformsRouteImport } from './routes/waveforms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchRoute = BranchRouteImport.update({
  id: '/branch',
  path: '/branch',
  getParentRoute: () => rootRouteImport,
} as any)
const CacheRoute = CacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => rootRouteImport,
} as any)
const FpgaRoute = FpgaRouteImport.update({
  id: '/fpga',
  path: '/fpga',
  getParentRoute: () => rootRouteImport,
} as any)
const HazardsRoute = HazardsRouteImport.update({
  id: '/hazards',
  path: '/hazards',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistersRoute = RegistersRouteImport.update({
  id: '/registers',
  path: '/registers',
  getParentRoute: () => rootRouteImport,
} as any)
const RtlExplorerRoute = RtlExplorerRouteImport.update({
  id: '/rtl-explorer',
  path: '/rtl-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const WaveformsRoute = WaveformsRouteImport.update({
  id: '/waveforms',
  path: '/waveforms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branch': typeof BranchRoute
  '/cache': typeof CacheRoute
  '/fpga': typeof FpgaRoute
  '/hazards': typeof HazardsRoute
  '/memory': typeof MemoryRoute
  '/performance': typeof PerformanceRoute
  '/pipeline': typeof PipelineRoute
  '/registers': typeof RegistersRoute
  '/rtl-explorer': typeof RtlExplorerRoute
  '/verification': typeof VerificationRoute
  '/waveforms': typeof WaveformsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branch': typeof BranchRoute
  '/cache': typeof CacheRoute
  '/fpga': typeof FpgaRoute
  '/hazards': typeof HazardsRoute
  '/memory': typeof MemoryRoute
  '/performance': typeof PerformanceRoute
  '/pipeline': typeof PipelineRoute
  '/registers': typeof RegistersRoute
  '/rtl-explorer': typeof RtlExplorerRoute
  '/verification': typeof VerificationRoute
  '/waveforms': typeof WaveformsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/branch': typeof BranchRoute
  '/cache': typeof CacheRoute
  '/fpga': typeof FpgaRoute
  '/hazards': typeof HazardsRoute
  '/memory': typeof MemoryRoute
  '/performance': typeof PerformanceRoute
  '/pipeline': typeof PipelineRoute
  '/registers': typeof RegistersRoute
  '/rtl-explorer': typeof RtlExplorerRoute
  '/verification': typeof VerificationRoute
  '/waveforms': typeof WaveformsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branch'
    | '/cache'
    | '/fpga'
    | '/hazards'
    | '/memory'
    | '/performance'
    | '/pipeline'
    | '/registers'
    | '/rtl-explorer'
    | '/verification'
    | '/waveforms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branch'
    | '/cache'
    | '/fpga'
    | '/hazards'
    | '/memory'
    | '/performance'
    | '/pipeline'
    | '/registers'
    | '/rtl-explorer'
    | '/verification'
    | '/waveforms'
  id:
    | '__root__'
    | '/'
    | '/branch'
    | '/cache'
    | '/fpga'
    | '/hazards'
    | '/memory'
    | '/performance'
    | '/pipeline'
    | '/registers'
    | '/rtl-explorer'
    | '/verification'
    | '/waveforms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BranchRoute: typeof BranchRoute
  CacheRoute: typeof CacheRoute
  FpgaRoute: typeof FpgaRoute
  HazardsRoute: typeof HazardsRoute
  MemoryRoute: typeof MemoryRoute
  PerformanceRoute: typeof PerformanceRoute
  PipelineRoute: typeof PipelineRoute
  RegistersRoute: typeof RegistersRoute
  RtlExplorerRoute: typeof RtlExplorerRoute
  VerificationRoute: typeof VerificationRoute
  WaveformsRoute: typeof WaveformsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch': {
      id: '/branch'
      path: '/branch'
      fullPath: '/branch'
      preLoaderRoute: typeof BranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cache': {
      id: '/cache'
      path: '/cache'
      fullPath: '/cache'
      preLoaderRoute: typeof CacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fpga': {
      id: '/fpga'
      path: '/fpga'
      fullPath: '/fpga'
      preLoaderRoute: typeof FpgaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hazards': {
      id: '/hazards'
      path: '/hazards'
      fullPath: '/hazards'
      preLoaderRoute: typeof HazardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registers': {
      id: '/registers'
      path: '/registers'
      fullPath: '/registers'
      preLoaderRoute: typeof RegistersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rtl-explorer': {
      id: '/rtl-explorer'
      path: '/rtl-explorer'
      fullPath: '/rtl-explorer'
      preLoaderRoute: typeof RtlExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waveforms': {
      id: '/waveforms'
      path: '/waveforms'
      fullPath: '/waveforms'
      preLoaderRoute: typeof WaveformsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BranchRoute: BranchRoute,
  CacheRoute: CacheRoute,
  FpgaRoute: FpgaRoute,
  HazardsRoute: HazardsRoute,
  MemoryRoute: MemoryRoute,
  PerformanceRoute: PerformanceRoute,
  PipelineRoute: PipelineRoute,
  RegistersRoute: RegistersRoute,
  RtlExplorerRoute: RtlExplorerRoute,
  VerificationRoute: VerificationRoute,
  WaveformsRoute: WaveformsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
